{% set name = "hvac" %}
{% set version = "0.9.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7e25794c6860155fa6f80420d7ac095e770c0d9088d7615048261574979267ec

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
    - requests >=2.21.0
  run:
    - python
    - requests >=2.21.0

test:
  imports:
    - hvac
    - hvac.api
    - hvac.api.auth_methods
    - hvac.api.secrets_engines
    - hvac.api.system_backend
    - hvac.constants
    - hvac.v1

about:
  home: https://python-hvac.org/
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE.txt
  summary: HashiCorp Vault API client
  doc_url: https://hvac.readthedocs.io/en/latest/?badge=latest
  dev_url: https://github.com/hvac/hvac

extra:
  recipe-maintainers:
    - mariusvniekerk
