{% set name = "hvac" %}
{% set version = "0.10.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 87dc2a3183c1d4595990203e752b430155d7582a60850dfe0756189a233d4b57

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
    - requests >=2.21.0
  run:
    - python
    - requests >=2.21.0

test:
  imports:
    - hvac
    - hvac.api
    - hvac.api.auth_methods
    - hvac.api.secrets_engines
    - hvac.api.system_backend
    - hvac.constants
    - hvac.v1

about:
  home: https://python-hvac.org/
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE.txt
  summary: HashiCorp Vault API client
  doc_url: https://hvac.readthedocs.io/en/latest/?badge=latest
  dev_url: https://github.com/hvac/hvac

extra:
  recipe-maintainers:
    - mariusvniekerk
